apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: default
  name: developer
  description : The developers
spec:
  type: team
  profile:
    displayName: Developer
    email: dev@example.com
children: []